CREATE TABLE IF NOT EXISTS rag_source_document (
    id CHAR(36) NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    source_reference_id VARCHAR(191) NOT NULL,
    clinic_id VARCHAR(191) NOT NULL,
    client_id VARCHAR(191) NOT NULL,
    pet_id VARCHAR(191) DEFAULT NULL,
    filename VARCHAR(255) NOT NULL,
    source_uri TEXT NOT NULL,
    source_checksum CHAR(64) NOT NULL,
    mime_type VARCHAR(191) NOT NULL,
    page_count INT NOT NULL,
    ingest_status VARCHAR(32) NOT NULL,
    ingest_error_code VARCHAR(191) DEFAULT NULL,
    ingest_error_detail TEXT DEFAULT NULL,
    pulled_at DATETIME(6) DEFAULT NULL,
    chunked_at DATETIME(6) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    modified_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY rag_source_document_source_ref_uniq (source_system, source_reference_id),
    UNIQUE KEY rag_source_document_client_pet_checksum_uniq (client_id, pet_id, source_checksum),
    KEY rag_source_document_client_id_idx (client_id),
    KEY rag_source_document_pet_id_idx (pet_id),
    KEY rag_source_document_status_idx (ingest_status),
    KEY rag_source_document_checksum_idx (source_checksum),
    CONSTRAINT rag_source_document_ingest_status_chk CHECK (
        ingest_status IN ('queued', 'running', 'succeeded', 'needs_review', 'failed', 'skipped')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
