"""Chunk Instinct patient PDFs and load enhanced chunks into pgvector.

The loader keeps the PDF pipeline inspectable:
- read a PDF from disk or URL
- extract page text, skipping image-only PDFs with a 204-style result
- detect medication, treatment, and product terms
- generate one clinical summary for the full PDF
- split page text into overlapping chunks
- attach summary and detected terms to each chunk's metadata
- load enhanced chunk rows into a Postgres/pgvector table

Embeddings are generated by a real provider so the stored vectors are ready for
production RAG workflows rather than benchmark-only placeholder math.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
import sys
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from pprint import pformat
from multiprocessing import get_context
from time import perf_counter
from collections.abc import Mapping, Sequence
from typing import Any, Iterable
from urllib import request as urllib_request
from urllib.parse import urlparse

import psycopg

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

try:
    from pypdf import PdfReader
except ImportError as exc:  # pragma: no cover - environment-specific dependency
    raise RuntimeError("pypdf is required to extract PDF text.") from exc

try:
    from pypdf.errors import PdfReadError
except Exception:  # pragma: no cover - pypdf version-specific import surface
    PdfReadError = Exception  # type: ignore[assignment]


DEFAULT_TABLE_NAME = "pms_page_chunk"
DEFAULT_SOURCE_DOCUMENT_TABLE_NAME = "rag_source_document"
DEFAULT_DEFERRED_OCR_TABLE_NAME = "rag_deferred_ocr_document"
DEFAULT_INGEST_STATE_TABLE_NAME = "rag_ingestion_run"
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"
DEFAULT_EMBEDDING_DIMENSIONS = 1536
DEFAULT_SCHEMA_VERSION = 2
SKIPPED_NO_TEXT_STATUS_CODE = 204
NO_TEXT_LAYER_ERROR = "PDF skipped: no extractable text layer found."
DEFAULT_TERM_TYPES = frozenset({"medication", "treatment", "product"})
DOC_FAMILIES = (
    "vaccine_history",
    "prescriptions",
    "communications",
    "antech_lab",
    "diagnoses",
    "wellness",
    "medical_notes",
    "transaction_history",
    "other",
)
DEFAULT_TEXT_CACHE_DIR = Path(os.environ.get("EVH_INSTINCT_TEXT_CACHE_DIR", "/tmp/evh_instinct_text_cache"))


class NoTextLayerError(RuntimeError):
    """Raised when a PDF has pages but no extractable text layer."""

    status_code = SKIPPED_NO_TEXT_STATUS_CODE

    def __init__(self, page_count: int) -> None:
        self.page_count = page_count
        super().__init__(f"{NO_TEXT_LAYER_ERROR} pages={page_count}")


class DeferredOCRDocument(RuntimeError):
    """Raised when a no-text-layer PDF should be deferred for later OCR."""

    def __init__(self, *, page_count: int, reason: str, metadata: dict[str, Any] | None = None) -> None:
        self.page_count = page_count
        self.reason = reason
        self.metadata = metadata or {}
        super().__init__(reason)


def _looks_like_non_pdf_or_corrupt_pdf(exc: Exception) -> bool:
    message = f"{type(exc).__name__}: {exc}".lower()
    return any(
        needle in message
        for needle in (
            "invalid pdf",
            "ole header",
            "pdfstreamerror",
            "pdf read error",
            "eof marker",
            "malformed",
            "not a valid pdf",
            "cannot read an empty file",
        )
    )


@dataclass(frozen=True)
class PatientPdfSource:
    patient_id: str
    patient_name: str
    pdf_path: Path | None = None
    pdf_url: str | None = None


@dataclass(frozen=True)
class ChunkingConfig:
    chunk_size: int = 1000
    chunk_overlap: int = 150

    def __post_init__(self) -> None:
        if self.chunk_size <= 0:
            raise ValueError("chunk_size must be positive")
        if self.chunk_overlap < 0:
            raise ValueError("chunk_overlap cannot be negative")
        if self.chunk_overlap >= self.chunk_size:
            raise ValueError("chunk_overlap must be smaller than chunk_size")


@dataclass(frozen=True)
class BenchmarkStats:
    source_name: str
    page_count: int
    chunk_count: int
    extraction_seconds: float
    chunking_seconds: float
    embedding_seconds: float
    load_seconds: float
    first_search_seconds: float
    vector_dimensions: int
    table_name: str


@dataclass(frozen=True)
class FetchedPdf:
    source_name: str
    source_uri: str | None
    pdf_bytes: bytes
    content_hash: str
    content_length: int


@dataclass(frozen=True)
class DictionaryTerm:
    term_type: str
    canonical_name: str
    aliases: tuple[str, ...]
    category: str | None = None
    confidence: float = 1.0


@dataclass(frozen=True)
class DetectedTerm:
    term_type: str
    canonical_name: str
    matched_text: str
    page_number: int
    count: int
    confidence: float


def fetch_instinct_pdf(source: PatientPdfSource) -> FetchedPdf:
    pdf_bytes = read_pdf_bytes(source)
    return FetchedPdf(
        source_name=source.patient_name,
        source_uri=source.pdf_url or (str(source.pdf_path) if source.pdf_path is not None else None),
        pdf_bytes=pdf_bytes,
        content_hash=hashlib.sha256(pdf_bytes).hexdigest(),
        content_length=len(pdf_bytes),
    )


def load_patient_manifest(path: Path) -> list[PatientPdfSource]:
    raw = path.read_text(encoding="utf-8")
    payload = json.loads(raw)
    if not isinstance(payload, list):
        raise ValueError("patient manifest must be a JSON array")

    entries: list[PatientPdfSource] = []
    for item in payload:
        if not isinstance(item, dict):
            raise ValueError("patient manifest entries must be JSON objects")

        patient_id = str(item.get("patient_id") or item.get("id") or "").strip()
        patient_name = str(item.get("patient_name") or item.get("name") or "").strip()
        pdf_value = item.get("pdf_path") or item.get("pdf")
        pdf_url = item.get("pdf_url") or item.get("source_url") or item.get("attachment_url")

        if not patient_id:
            raise ValueError(f"manifest entry is missing patient_id: {item!r}")
        if not patient_name:
            raise ValueError(f"manifest entry is missing patient_name: {item!r}")

        pdf_path = Path(pdf_value) if isinstance(pdf_value, str) and pdf_value.strip() else None
        if pdf_path is None and not (isinstance(pdf_url, str) and pdf_url.strip()):
            raise ValueError(f"manifest entry is missing pdf_path or pdf_url: {item!r}")

        entries.append(
            PatientPdfSource(
                patient_id=patient_id,
                patient_name=patient_name,
                pdf_path=pdf_path,
                pdf_url=pdf_url if isinstance(pdf_url, str) and pdf_url.strip() else None,
            )
        )

    return entries


def read_pdf_bytes(source: PatientPdfSource) -> bytes:
    if source.pdf_url:
        import requests

        response = requests.get(source.pdf_url, timeout=60)
        response.raise_for_status()
        return response.content
    if source.pdf_path is None:
        raise ValueError("patient PDF source must include pdf_path or pdf_url")
    return source.pdf_path.read_bytes()


def _source_suffix(source: PatientPdfSource) -> str:
    if source.pdf_path is not None:
        return source.pdf_path.suffix.lower()
    if source.pdf_url:
        return Path(urlparse(source.pdf_url).path).suffix.lower()
    return ""


def _detect_word_parser() -> tuple[str | None, str | None]:
    for name in ("antiword", "catdoc", "libreoffice", "soffice"):
        path = shutil.which(name)
        if path:
            if name == "soffice":
                name = "libreoffice"
            return name, path
    return None, None


def _cache_key_for_source(source: PatientPdfSource, payload: bytes | None = None) -> str:
    hasher = hashlib.sha256()
    hasher.update((source.pdf_path.name if source.pdf_path is not None else source.pdf_url or "").encode("utf-8"))
    if payload is not None:
        hasher.update(payload)
    return hasher.hexdigest()


def _load_cached_text_pages(cache_dir: Path, cache_key: str) -> tuple[list[str], int] | None:
    cache_file = cache_dir / f"{cache_key}.json"
    if not cache_file.exists():
        return None
    try:
        payload = json.loads(cache_file.read_text(encoding="utf-8"))
        pages = payload.get("pages")
        page_count = int(payload.get("page_count") or 0)
        if isinstance(pages, list):
            return [str(page) for page in pages], page_count or len(pages)
    except Exception:
        return None
    return None


def _store_cached_text_pages(cache_dir: Path, cache_key: str, pages: list[str], page_count: int, *, parser: str) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file = cache_dir / f"{cache_key}.json"
    cache_file.write_text(
        json.dumps(
            {
                "parser": parser,
                "page_count": page_count,
                "pages": pages,
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


def _extract_word_text_pages(source: PatientPdfSource, *, pdf_bytes: bytes | None = None) -> tuple[list[str], int, str]:
    if source.pdf_path is None and pdf_bytes is None:
        raise RuntimeError("Word-document fallback requires either a local file path or downloaded bytes")
    if source.pdf_path is not None:
        path = source.pdf_path
        temp_dir_ctx = None
    else:
        temp_dir_ctx = tempfile.TemporaryDirectory(prefix="instinct-doc-src-")
        temp_path = Path(temp_dir_ctx.__enter__())
        path = temp_path / "source.doc"
        path.write_bytes(pdf_bytes or b"")
    parser_name, parser_path = _detect_word_parser()
    if parser_name == "antiword" and parser_path:
        proc = subprocess.run([parser_path, str(path)], check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        text = proc.stdout.decode("utf-8", errors="replace")
    elif parser_name == "catdoc" and parser_path:
        proc = subprocess.run([parser_path, str(path)], check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        text = proc.stdout.decode("utf-8", errors="replace")
    elif parser_name == "libreoffice" and parser_path:
        with tempfile.TemporaryDirectory(prefix="instinct-doc-") as temp_dir:
            temp_path = Path(temp_dir)
            proc = subprocess.run(
                [
                    parser_path,
                    "--headless",
                    "--convert-to",
                    "txt:Text",
                    "--outdir",
                    str(temp_path),
                    str(path),
                ],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            _ = proc
            txt_files = sorted(temp_path.glob("*.txt"))
            if not txt_files:
                raise RuntimeError("LibreOffice DOC conversion produced no text output")
            text = txt_files[0].read_text(encoding="utf-8", errors="replace")
    else:
        raise RuntimeError("No DOC parser available (antiword, catdoc, or libreoffice)")

    try:
        pages = [chunk.strip() for chunk in re.split(r"\f+", text) if chunk.strip()]
        if not pages:
            pages = [(text or "").strip()]
        return pages, len(pages), parser_name or "unknown"
    finally:
        if temp_dir_ctx is not None:
            temp_dir_ctx.__exit__(None, None, None)


def read_pdf_text_from_source(source: PatientPdfSource) -> tuple[list[str], int]:
    pdf_bytes = read_pdf_bytes(source)
    try:
        return extract_pdf_text_pages(pdf_bytes)
    except NoTextLayerError:
        return ocr_pdf_text_pages(pdf_bytes)


def _extract_pdf_text_pages_worker(pdf_bytes: bytes, queue) -> None:
    try:
        pages, page_count = extract_pdf_text_pages(pdf_bytes)
        queue.put(("ok", {"pages": pages, "page_count": page_count}))
    except NoTextLayerError as exc:
        queue.put(
            (
                "no_text",
                {
                    "page_count": exc.page_count,
                    "error": str(exc),
                },
            )
        )
    except Exception as exc:  # pragma: no cover - child process
        queue.put(
            (
                "err",
                {
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                },
            )
        )


def safe_extract_pdf_text_pages(pdf_bytes: bytes, *, timeout_s: int = 120) -> tuple[list[str], int]:
    ctx = get_context("spawn")
    queue = ctx.Queue()
    proc = ctx.Process(target=_extract_pdf_text_pages_worker, args=(pdf_bytes, queue), daemon=True)
    proc.start()
    proc.join(timeout_s)
    if proc.is_alive():
        proc.terminate()
        proc.join(10)
        if proc.is_alive():
            proc.kill()
            proc.join(5)
        raise RuntimeError(f"PDF text extraction exceeded {timeout_s} seconds")
    if queue.empty():
        rc = proc.exitcode
        if rc is not None and rc < 0:
            raise RuntimeError(f"PDF text extraction crashed with signal {-rc}")
        raise RuntimeError("PDF text extraction worker returned no payload")
    status, payload = queue.get()
    if status == "no_text":
        raise NoTextLayerError(int(payload.get("page_count") or 0))
    if status != "ok":
        raise RuntimeError(f"PDF text extraction failed: {payload.get('error_type')}: {payload.get('error')}")
    return payload["pages"], int(payload["page_count"])


def ocr_pdf_text_pages(pdf_bytes: bytes) -> tuple[list[str], int]:
    gs_command = shutil.which("gs") or shutil.which("ghostscript")
    tesseract_command = shutil.which("tesseract")
    if not gs_command or not tesseract_command:
        raise NoTextLayerError(page_count=0)

    with tempfile.TemporaryDirectory(prefix="instinct-ocr-") as temp_dir:
        temp_path = Path(temp_dir)
        pdf_path = temp_path / "source.pdf"
        pdf_path.write_bytes(pdf_bytes)
        output_prefix = temp_path / "page"
        raster_cmd = [
            gs_command,
            "-dNOPAUSE",
            "-dBATCH",
            "-sDEVICE=png16m",
            "-r200",
            f"-sOutputFile={output_prefix}-%03d.png",
            str(pdf_path),
        ]
        subprocess.run(raster_cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        page_files = sorted(temp_path.glob("page-*.png"))
        if not page_files:
            raise NoTextLayerError(page_count=0)

        pages: list[str] = []
        for image_path in page_files:
            proc = subprocess.run(
                [tesseract_command, str(image_path), "stdout", "--psm", "6"],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
            )
            pages.append((proc.stdout.decode("utf-8", errors="replace") or "").strip())

        return pages, len(pages)


def extract_pdf_text_pages(pdf_bytes: bytes) -> tuple[list[str], int]:
    reader = PdfReader(BytesIO(pdf_bytes))
    page_count = len(reader.pages)

    pages: list[str] = []
    for page in reader.pages:
        try:
            text = page.extract_text(extraction_mode="layout")
        except Exception:
            text = page.extract_text()
        pages.append((text or "").strip())

    if page_count and not any(page_text.strip() for page_text in pages):
        raise NoTextLayerError(page_count)
    return pages, page_count


def _split_aliases(raw_aliases: str | None) -> tuple[str, ...]:
    if raw_aliases is None:
        return ()
    raw_aliases = raw_aliases.strip()
    if not raw_aliases:
        return ()
    if raw_aliases.startswith("["):
        try:
            payload = json.loads(raw_aliases)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, list):
            return tuple(str(item).strip() for item in payload if str(item).strip())
    return tuple(alias.strip() for alias in raw_aliases.split(",") if alias.strip())


def _parse_bool(value: str | None) -> bool:
    return str(value or "").strip().lower() not in {"0", "false", "no", "inactive"}


def _aws_data_api_query(sql: str) -> list[dict[str, Any]]:
    cluster_arn = os.environ.get("DB_CLUSTER_ARN")
    secret_arn = os.environ.get("DB_SECRET_ARN")
    database = os.environ.get("DB_NAME")
    if not cluster_arn or not secret_arn or not database:
        raise RuntimeError("DB_CLUSTER_ARN, DB_SECRET_ARN, and DB_NAME must be set.")

    last_error = ""
    for attempt in range(5):
        proc = subprocess.run(
            [
                "aws",
                "rds-data",
                "execute-statement",
                "--resource-arn",
                cluster_arn,
                "--secret-arn",
                secret_arn,
                "--database",
                database,
                "--sql",
                sql,
                "--include-result-metadata",
                "--format-records-as",
                "JSON",
            ],
            capture_output=True,
            text=True,
        )
        if proc.returncode == 0:
            payload = json.loads(proc.stdout or "{}")
            return json.loads(payload.get("formattedRecords", "[]"))

        last_error = (proc.stderr or proc.stdout or "").strip()
        if "DatabaseResumingException" in last_error and attempt < 4:
            time.sleep(2 * (attempt + 1))
            continue
        break
    raise RuntimeError(last_error or "AWS Data API query failed")


def find_default_dictionary_csv() -> Path | None:
    worktree_root = Path(__file__).resolve().parents[1]
    worktrees_root = worktree_root.parent
    candidates = [
        worktrees_root / "aj" / "db" / "rag_dictionary_term_seed_merged.csv",
        worktrees_root / "rarity" / "docs" / "aj-rag-dictionary-term-seed.csv",
        worktrees_root / "rarity" / "docs" / "rarity-meds-treatments-canonical.csv",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def built_in_term_index() -> list[DictionaryTerm]:
    return [
        DictionaryTerm("medication", "Apoquel", ("Apoquel",), "fallback-medication", 0.85),
        DictionaryTerm("medication", "Carprofen", ("Carprofen", "Rimadyl"), "fallback-medication", 0.85),
        DictionaryTerm("medication", "Cytopoint", ("Cytopoint",), "fallback-medication", 0.85),
        DictionaryTerm("medication", "Librela", ("Librela",), "fallback-medication", 0.85),
        DictionaryTerm("treatment", "Dental cleaning", ("dental cleaning", "dental prophylaxis"), "fallback-treatment", 0.85),
        DictionaryTerm("treatment", "Surgery", ("surgery", "surgical", "spay", "neuter"), "fallback-treatment", 0.85),
        DictionaryTerm("product", "Heartgard Plus", ("Heartgard Plus",), "fallback-product", 0.85),
        DictionaryTerm("product", "NexGard", ("NexGard", "Nexgard Plus"), "fallback-product", 0.85),
    ]


def load_term_index(
    dictionary_csv: Path | None = None,
    *,
    term_types: set[str] | frozenset[str] = DEFAULT_TERM_TYPES,
) -> list[DictionaryTerm]:
    if dictionary_csv is None:
        return built_in_term_index()
    try:
        rows = _aws_data_api_query(
            """
SELECT canonical_name, aliases, term_type, category, confidence_score
FROM rag_dictionary_term
WHERE active = 1
ORDER BY priority_score DESC, canonical_name;
""".strip()
        )
        alias_rows = _aws_data_api_query(
            """
SELECT t.term_type, t.canonical_name, a.alias_text
FROM rag_dictionary_term_alias a
JOIN rag_dictionary_term t ON t.id = a.dictionary_term_id
WHERE t.active = 1
ORDER BY t.priority_score DESC, t.canonical_name, a.alias_text;
""".strip()
        )

        alias_map: dict[tuple[str, str], list[str]] = {}
        for row in alias_rows:
            key = (str(row.get("term_type") or "").strip(), str(row.get("canonical_name") or "").strip())
            alias_map.setdefault(key, [])
            alias_text = str(row.get("alias_text") or "").strip()
            if alias_text and alias_text not in alias_map[key]:
                alias_map[key].append(alias_text)

        terms: list[DictionaryTerm] = []
        for row in rows:
            term_type = str(row.get("term_type") or "").strip().lower()
            canonical_name = str(row.get("canonical_name") or "").strip()
            if term_type not in term_types or not canonical_name:
                continue
            if not _parse_bool(str(row.get("active", "1"))):
                continue
            try:
                confidence = float(row.get("confidence_score") or 1.0)
            except ValueError:
                confidence = 1.0
            aliases = list(dict.fromkeys([canonical_name]))
            raw_aliases = row.get("aliases")
            if isinstance(raw_aliases, str):
                aliases.extend(_split_aliases(raw_aliases))
            aliases.extend(alias_map.get((term_type, canonical_name), []))
            terms.append(
                DictionaryTerm(
                    term_type=term_type,
                    canonical_name=canonical_name,
                    aliases=tuple(dict.fromkeys(alias.strip() for alias in aliases if alias.strip())),
                    category=str(row.get("category") or "").strip() or None,
                    confidence=confidence,
                )
            )
        if terms:
            return terms
    except Exception:
        pass

    path = dictionary_csv or find_default_dictionary_csv()
    if path is None:
        return built_in_term_index()

    terms: list[DictionaryTerm] = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            term_type = str(row.get("term_type") or "").strip().lower()
            canonical_name = str(row.get("canonical_name") or "").strip()
            if term_type not in term_types or not canonical_name or not _parse_bool(row.get("active")):
                continue
            try:
                confidence = float(row.get("confidence") or row.get("confidence_score") or 1.0)
            except ValueError:
                confidence = 1.0
            aliases = tuple(dict.fromkeys((canonical_name, *_split_aliases(row.get("aliases")))))
            terms.append(
                DictionaryTerm(
                    term_type=term_type,
                    canonical_name=canonical_name,
                    aliases=aliases,
                    category=str(row.get("category") or "").strip() or None,
                    confidence=confidence,
                )
            )
    return terms or built_in_term_index()


def detect_terms_in_text(text: str, terms: Iterable[DictionaryTerm], *, page_number: int) -> list[DetectedTerm]:
    detected: dict[tuple[str, str, str], DetectedTerm] = {}
    lowered_text = text.lower()
    for term in terms:
        for alias in term.aliases:
            alias = str(alias).strip()
            if len(alias) < 3:
                continue
            alias = alias.encode("utf-8", "ignore").decode("utf-8", "ignore")
            if len(alias) < 3:
                continue
            alias_lower = alias.lower()
            count = lowered_text.count(alias_lower)
            if not count:
                continue
            matched_text = alias
            key = (term.term_type, term.canonical_name, alias_lower)
            detected[key] = DetectedTerm(
                term_type=term.term_type,
                canonical_name=term.canonical_name,
                matched_text=matched_text,
                page_number=page_number,
                count=count,
                confidence=term.confidence,
            )
    return sorted(detected.values(), key=lambda item: (item.term_type, item.canonical_name, item.matched_text))


def detected_terms_to_metadata(terms: Iterable[DetectedTerm]) -> list[dict[str, Any]]:
    return [
        {
            "term_type": term.term_type,
            "canonical_name": term.canonical_name,
            "matched_text": term.matched_text,
            "page_number": term.page_number,
            "count": term.count,
            "confidence": term.confidence,
        }
        for term in terms
    ]


def summarize_detected_terms(terms: Iterable[DetectedTerm]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {"medication": [], "treatment": [], "product": []}
    for term in terms:
        grouped.setdefault(term.term_type, [])
        if term.canonical_name not in grouped[term.term_type]:
            grouped[term.term_type].append(term.canonical_name)
    return {key: sorted(values) for key, values in grouped.items() if values}


def _normalize_table_text(text: str) -> str:
    lines = [re.sub(r"\s+", " ", line).strip() for line in text.splitlines()]
    return "\n".join(line for line in lines if line)


def _is_date_token(token: str) -> bool:
    return bool(re.fullmatch(r"\d{1,2}/\d{1,2}/\d{2,4}", token))


def _extract_table_records(
    pages: list[str],
    term_summary: dict[str, list[str]],
    *,
    family: str | None = None,
) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    known_terms = [term for values in term_summary.values() for term in values]
    for page_text in pages:
        raw_lines = [line.rstrip() for line in page_text.splitlines() if line.strip()]
        if not raw_lines:
            continue
        normalized_lines = [re.sub(r"\s+", " ", line).strip() for line in raw_lines]
        if not any(normalized_lines):
            continue

        if family == "transaction_history":
            header_seen = False
            row_lines: list[str] = []
            for line in normalized_lines:
                if not line:
                    continue
                lower = line.lower()
                if "date provider patient product" in lower or "date provider" in lower and "amount" in lower:
                    header_seen = True
                    continue
                if not header_seen:
                    continue
                if re.match(r"^\d{1,2}/\d{1,2}/\d{2,4}\b", line):
                    if row_lines:
                        records.append(_parse_transaction_history_row(" ".join(row_lines), known_terms))
                    row_lines = [line]
                elif row_lines:
                    row_lines.append(line)
            if row_lines:
                records.append(_parse_transaction_history_row(" ".join(row_lines), known_terms))
            continue

        if family == "antech_lab":
            current_block: list[str] = []
            for line in normalized_lines:
                lower = line.lower()
                if "date:" in lower and current_block and any("code name" in part.lower() for part in current_block):
                    records.append(_parse_lab_history_block(current_block, known_terms))
                    current_block = [line]
                    continue
                if "lab test history" in lower or "name result unit indicator" in lower or "reference low" in lower:
                    current_block.append(line)
                    continue
                if current_block:
                    current_block.append(line)
            if current_block:
                records.append(_parse_lab_history_block(current_block, known_terms))
            continue

        blocks: list[list[str]] = []
        current_block: list[str] = []
        for raw_line in normalized_lines:
            if not raw_line:
                continue
            if "codename" in raw_line.lower() and "provider" in raw_line.lower():
                continue
            if re.match(r"^(RK|KA|BORAO)\b", raw_line):
                if current_block:
                    blocks.append(current_block)
                current_block = [raw_line]
                continue
            if current_block:
                current_block.append(raw_line)
        if current_block:
            blocks.append(current_block)

        for block in blocks:
            raw_line = " ".join(block)
            if not re.match(r"^(RK|KA|BORAO)\b", raw_line):
                continue
            code = raw_line.split()[0]
            dates = re.findall(r"\b\d{1,2}/\d{1,2}/\d{2,4}\b", raw_line)
            provider = "Christine B. Cassidy, DVM" if "Christine B." in raw_line and "Cassidy" in raw_line and "DVM" in raw_line else ""
            row_terms = [term for term in known_terms if term.lower() in raw_line.lower()]
            description = ""
            if "Imrab 1" in raw_line:
                description = "Imrab 1 Rabies Canine 1yr"
            elif "DA2P" in raw_line:
                description = "DA2P + Leptospirosis 4 Annual" if "Leptospirosis" in raw_line else "DA2P Annual"
            elif "Bordetella" in raw_line:
                description = "Bordetella Oral Vaccine"
            records.append(
                {
                    "code": code,
                    "dates": ", ".join(dates),
                    "provider": provider,
                    "description": description,
                    "terms": ", ".join(row_terms),
                    "raw": raw_line,
                }
            )
    return records


def _parse_transaction_history_row(row_text: str, known_terms: list[str]) -> dict[str, str]:
    text = re.sub(r"\s+", " ", row_text).strip()
    dates = re.findall(r"\b\d{1,2}/\d{1,2}/\d{2,4}\b", text)
    provider = ""
    provider_match = re.search(r"\b([A-Z][a-z]+(?: [A-Z]\.)?(?: [A-Z][a-z]+)?(?:, DVM)?)\b", text)
    if provider_match and "date" not in provider_match.group(1).lower():
        provider = provider_match.group(1)
    product = ""
    if " physical exam" in text.lower():
        product = "Physical Exam"
    elif " vaccine" in text.lower():
        product = "Vaccine"
    elif " labs" in text.lower() or "lab" in text.lower():
        product = "Lab"
    row_terms = [term for term in known_terms if term.lower() in text.lower()]
    return {
        "code": dates[0] if dates else "",
        "dates": ", ".join(dates),
        "provider": provider,
        "description": product,
        "terms": ", ".join(row_terms),
        "raw": text,
    }


def _parse_lab_history_block(block_lines: list[str], known_terms: list[str]) -> dict[str, str]:
    text = _normalize_table_text("\n".join(block_lines))
    lines = [line for line in text.splitlines() if line.strip()]
    header = next((line for line in lines if "name" in line.lower() and "result" in line.lower()), "")
    code = ""
    description = ""
    provider = ""
    dates = re.findall(r"\b\d{1,2}/\d{1,2}/\d{2,4}\b", text)
    for line in lines:
        if line.lower().startswith("code name:"):
            code = line.split(":", 1)[1].strip().split()[0] if ":" in line else ""
        elif line.lower().startswith("description:"):
            description = line.split(":", 1)[1].strip()
        elif line.lower().startswith("provider:") and line.split(":", 1)[1].strip():
            provider = line.split(":", 1)[1].strip()
        elif line.lower().startswith("provider:") and not provider:
            continue
    if not code and header:
        code = "LAB"
    row_terms = [term for term in known_terms if term.lower() in text.lower()]
    return {
        "code": code,
        "dates": ", ".join(dict.fromkeys(dates)),
        "provider": provider,
        "description": description,
        "terms": ", ".join(row_terms),
        "raw": text,
    }


def _extract_text_excerpt(text: str, *, max_chars: int = 280) -> str:
    compact_text = re.sub(r"\s+", " ", text).strip()
    if not compact_text:
        return ""
    end_positions = [compact_text.find(marker, 1) for marker in (". ", "! ", "? ")]
    end_positions = [position for position in end_positions if position != -1]
    if end_positions:
        cutoff = min(end_positions) + 1
        excerpt = compact_text[:cutoff].strip()
    else:
        excerpt = compact_text[:max_chars].strip()
    return excerpt[:max_chars].rstrip()


def _is_requisition_order(pages: list[str]) -> bool:
    haystack = "\n".join(page for page in pages if page.strip()).lower()
    return "antech requisition order" in haystack or "requisition order" in haystack


def _looks_like_cbc_or_lab_report(pages: list[str]) -> bool:
    haystack = "\n".join(page for page in pages if page.strip()).lower()
    return "cbc" in haystack or "complete blood count" in haystack or "lab results" in haystack or "hematology" in haystack


def _summarize_abnormal_lab_lines(pages: list[str]) -> str:
    abnormal_lines: list[str] = []
    for page in pages:
        for raw_line in page.splitlines():
            line = re.sub(r"\s+", " ", raw_line).strip()
            if not line:
                continue
            lowered = line.lower()
            if any(token in lowered for token in (" high", " low", " h ", " l ", "abnormal", "out of range", "elevated", "decreased", "critical", "*")):
                if len(line) > 280:
                    line = line[:277].rstrip() + "..."
                abnormal_lines.append(line)
    if not abnormal_lines:
        return ""
    unique_lines: list[str] = []
    seen: set[str] = set()
    for line in abnormal_lines:
        if line not in seen:
            unique_lines.append(line)
            seen.add(line)
    return "Abnormal findings: " + " | ".join(unique_lines[:10]) + "."


def _detect_document_family(source: PatientPdfSource, pages: list[str]) -> str:
    haystack = " ".join(
        [
            source.patient_name,
            source.pdf_url or "",
            source.pdf_path.name if source.pdf_path is not None else "",
            " ".join(page[:600] for page in pages[:2]),
        ]
    ).lower()
    if "vaccine history" in haystack or "vaccinehistory" in haystack:
        return "vaccine_history"
    if "prescriptions" in haystack or "prescription" in haystack or "rx" in haystack:
        return "prescriptions"
    if "communications" in haystack:
        return "communications"
    if "diagnoses" in haystack:
        return "diagnoses"
    if "transaction history" in haystack:
        return "transaction_history"
    if "lab test history" in haystack or "labresults" in haystack:
        return "antech_lab"
    if "medical note history" in haystack or "medical notes" in haystack:
        return "medical_notes"
    if "wellness" in haystack:
        return "wellness"
    return "other"


def _family_summary_mode(family: str) -> str:
    if family in {"antech_lab", "transaction_history"}:
        return "structured_only"
    if family in {"medical_notes", "wellness"}:
        return "clinical_summary"
    return "clinical_summary"


def _build_document_summary(
    source: PatientPdfSource,
    pages: list[str],
    detected_terms: Iterable[DetectedTerm],
    *,
    family: str,
) -> tuple[str, str]:
    mode = _family_summary_mode(family)
    if _is_requisition_order(pages):
        return "", "structured_only"
    if mode == "structured_only":
        if _looks_like_cbc_or_lab_report(pages):
            abnormal = _summarize_abnormal_lab_lines(pages)
            return abnormal, "abnormal_only" if abnormal else "structured_only"
        return "", "structured_only"
    if _looks_like_cbc_or_lab_report(pages):
        abnormal = _summarize_abnormal_lab_lines(pages)
        return abnormal, "abnormal_only" if abnormal else "structured_only"
    summary = generate_veterinary_clinical_summary(source, pages, detected_terms, family=family)
    return summary, "clinical_summary" if len(pages) <= 8 else "patient_history"


def generate_veterinary_clinical_summary(
    source: PatientPdfSource,
    pages: list[str],
    detected_terms: Iterable[DetectedTerm],
    *,
    family: str = "",
    max_preview_chars: int = 360,
) -> str:
    term_summary = summarize_detected_terms(detected_terms)
    full_text = "\n".join(page for page in pages if page.strip())
    excerpt = _extract_text_excerpt(full_text, max_chars=max_preview_chars)
    page_count = len(pages)
    table_records = _extract_table_records(pages, term_summary, family=family)
    summary_bits: list[str] = []
    if term_summary.get("medication"):
        summary_bits.append("Medications: " + ", ".join(term_summary["medication"][:12]) + ".")
    if term_summary.get("treatment"):
        summary_bits.append("Treatments: " + ", ".join(term_summary["treatment"][:12]) + ".")
    if term_summary.get("product"):
        summary_bits.append("Products: " + ", ".join(term_summary["product"][:12]) + ".")

    if page_count > 8:
        sections = [
            f"Patient history summary for {source.patient_name} ({source.patient_id}) across {page_count} pages."
        ]
        if summary_bits:
            sections.append("History signals: " + " ".join(summary_bits))
        if table_records:
            rows = []
            for record in table_records[:6]:
                row_bits = [record["code"]]
                if record["dates"]:
                    row_bits.append(record["dates"])
                if record["provider"]:
                    row_bits.append(record["provider"])
                if record["description"]:
                    row_bits.append(record["description"])
                rows.append("; ".join(row_bits))
            sections.append("Table rows: " + " | ".join(rows))
        if excerpt:
            sections.append("Historical excerpt: " + excerpt)
        return " ".join(sections)

    sections = [f"Clinical summary for {source.patient_name} ({source.patient_id}) from {page_count} page(s)."]
    if summary_bits:
        sections.append("Key signals: " + " ".join(summary_bits))
    if table_records:
        rows = []
        for record in table_records[:6]:
            row_bits = [record["code"]]
            if record["dates"]:
                row_bits.append(record["dates"])
            if record["provider"]:
                row_bits.append(record["provider"])
            if record["description"]:
                row_bits.append(record["description"])
            rows.append("; ".join(row_bits))
        sections.append("Table rows: " + " | ".join(rows))
    if excerpt:
        sections.append("Clinical excerpt: " + excerpt)
    return " ".join(sections)


def split_text(text: str, *, chunk_size: int, chunk_overlap: int) -> list[str]:
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\f", "\n\n", "\n", ". ", "? ", "! ", "; ", ": ", " ", ""],
    )
    return splitter.split_text(text)


def chunk_pdf_pages(
    source: PatientPdfSource,
    pages: list[str],
    config: ChunkingConfig,
    *,
    term_index: Iterable[DictionaryTerm] | None = None,
) -> list[Document]:
    terms = list(term_index) if term_index is not None else load_term_index()
    family = _detect_document_family(source, pages)
    full_pdf_terms: list[DetectedTerm] = []
    page_terms_by_number: dict[int, list[DetectedTerm]] = {}
    for page_number, page_text in enumerate(pages, start=1):
        page_terms = detect_terms_in_text(page_text, terms, page_number=page_number)
        page_terms_by_number[page_number] = page_terms
        full_pdf_terms.extend(page_terms)

    clinical_summary, summary_style = _build_document_summary(source, pages, full_pdf_terms, family=family)
    full_pdf_terms_metadata = detected_terms_to_metadata(full_pdf_terms)
    term_summary = summarize_detected_terms(full_pdf_terms)
    table_records = _extract_table_records(pages, term_summary, family=family)

    documents: list[Document] = []
    chunk_index = 1
    for page_number, page_text in enumerate(pages, start=1):
        for chunk_text in split_text(page_text, chunk_size=config.chunk_size, chunk_overlap=config.chunk_overlap):
            chunk_terms = detect_terms_in_text(chunk_text, terms, page_number=page_number)
            documents.append(
                Document(
                    page_content=chunk_text,
                    metadata={
                        "patient_id": source.patient_id,
                        "patient_name": source.patient_name,
                        "pdf_path": str(source.pdf_path) if source.pdf_path is not None else None,
                        "pdf_url": source.pdf_url,
                        "page_number": page_number,
                        "chunk_index": chunk_index,
                        "source": "instinct-patient-pdf",
                        "document_family": family,
                        "clinical_summary": clinical_summary,
                        "clinical_summary_style": summary_style,
                        "term_summary": term_summary,
                        "table_records": table_records,
                        "detected_terms": detected_terms_to_metadata(chunk_terms),
                        "page_detected_terms": detected_terms_to_metadata(page_terms_by_number.get(page_number, [])),
                        "full_pdf_detected_terms": full_pdf_terms_metadata,
                    },
                )
            )
            chunk_index += 1
    return documents


def chunk_patient_pdf(
    source: PatientPdfSource,
    config: ChunkingConfig,
    *,
    term_index: Iterable[DictionaryTerm] | None = None,
) -> tuple[list[Document], int]:
    pages, page_count = read_pdf_text_from_source(source)
    return chunk_pdf_pages(source, pages, config, term_index=term_index), page_count


def chunk_patient_pdf_timed(
    source: PatientPdfSource,
    config: ChunkingConfig,
    *,
    term_index: Iterable[DictionaryTerm] | None = None,
    defer_no_text_page_threshold: int | None = 8,
) -> tuple[list[Document], int, dict[str, float]]:
    download_start = perf_counter()
    pdf_bytes = read_pdf_bytes(source)
    download_seconds = perf_counter() - download_start
    cache_key = _cache_key_for_source(source, pdf_bytes)
    cache_dir = DEFAULT_TEXT_CACHE_DIR
    suffix = _source_suffix(source)

    cached = _load_cached_text_pages(cache_dir, cache_key)
    if cached is not None:
        pages, page_count = cached
        extraction_seconds = 0.0
        chunking_start = perf_counter()
        documents = chunk_pdf_pages(source, pages, config, term_index=term_index)
        chunking_seconds = perf_counter() - chunking_start
        summary_seconds = chunking_seconds if documents else 0.0
        return documents, page_count, {
            "download_seconds": download_seconds,
            "extraction_seconds": extraction_seconds,
            "chunking_seconds": chunking_seconds,
            "summary_seconds": summary_seconds,
        }

    extraction_start = perf_counter()
    try:
        if suffix in {".doc", ".docx"}:
            pages, page_count, parser_name = _extract_word_text_pages(source, pdf_bytes=pdf_bytes)
            _store_cached_text_pages(cache_dir, cache_key, pages, page_count, parser=parser_name)
            extraction_seconds = perf_counter() - extraction_start
            chunking_start = perf_counter()
            documents = chunk_pdf_pages(source, pages, config, term_index=term_index)
            chunking_seconds = perf_counter() - chunking_start
            summary_seconds = chunking_seconds if documents else 0.0
            return documents, page_count, {
                "download_seconds": download_seconds,
                "extraction_seconds": extraction_seconds,
                "chunking_seconds": chunking_seconds,
                "summary_seconds": summary_seconds,
            }
        pages, page_count = safe_extract_pdf_text_pages(pdf_bytes)
        _store_cached_text_pages(cache_dir, cache_key, pages, page_count, parser="pypdf")
    except (PdfReadError, RuntimeError, ValueError, OSError) as exc:
        if _looks_like_non_pdf_or_corrupt_pdf(exc):
            raise DeferredOCRDocument(
                page_count=0,
                reason=f"Deferred non-PDF or corrupt PDF ({type(exc).__name__}: {exc})",
                metadata={
                    "patient_id": source.patient_id,
                    "patient_name": source.patient_name,
                    "pdf_url": source.pdf_url,
                    "pdf_path": str(source.pdf_path) if source.pdf_path is not None else None,
                    "filename": source.pdf_path.name if source.pdf_path is not None else None,
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                    "action": "defer_non_pdf_or_corrupt_pdf",
                },
            ) from exc
        raise
    except NoTextLayerError:
        page_count = 0
        try:
            page_count = PdfReader(BytesIO(pdf_bytes)).getNumPages()  # type: ignore[attr-defined]
        except Exception:
            try:
                page_count = len(PdfReader(BytesIO(pdf_bytes)).pages)
            except Exception:
                page_count = 0
        if defer_no_text_page_threshold is not None and page_count >= defer_no_text_page_threshold:
            raise DeferredOCRDocument(
                page_count=page_count,
                reason=f"Deferred OCR for large no-text-layer PDF (pages={page_count})",
                metadata={
                    "patient_id": source.patient_id,
                    "patient_name": source.patient_name,
                    "pdf_url": source.pdf_url,
                    "pdf_path": str(source.pdf_path) if source.pdf_path is not None else None,
                    "filename": source.pdf_path.name if source.pdf_path is not None else None,
                },
            )
        pages, page_count = ocr_pdf_text_pages(pdf_bytes)
    extraction_seconds = perf_counter() - extraction_start

    chunking_start = perf_counter()
    documents = chunk_pdf_pages(source, pages, config, term_index=term_index)
    chunking_seconds = perf_counter() - chunking_start

    summary_seconds = 0.0
    if documents:
        # Summary generation is already embedded in chunk_pdf_pages; estimate via
        # the chunking wall clock for now and expose a dedicated bucket for future
        # stage splits.
        summary_seconds = chunking_seconds

    return documents, page_count, {
        "download_seconds": download_seconds,
        "extraction_seconds": extraction_seconds,
        "chunking_seconds": chunking_seconds,
        "summary_seconds": summary_seconds,
    }


def chunk_patient_manifest(
    manifest: Iterable[PatientPdfSource],
    config: ChunkingConfig,
    *,
    term_index: Iterable[DictionaryTerm] | None = None,
) -> tuple[list[Document], int]:
    documents: list[Document] = []
    page_count = 0
    terms = list(term_index) if term_index is not None else load_term_index()
    for source in manifest:
        source_documents, source_pages = chunk_patient_pdf(source, config, term_index=terms)
        documents.extend(source_documents)
        page_count += source_pages
    return documents, page_count


def _openai_api_key() -> str:
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is required for real embedding generation. "
            "Set it before running the PDF ingest pipeline."
        )
    return api_key


def embed_texts_openai(
    texts: list[str],
    *,
    model: str = DEFAULT_EMBEDDING_MODEL,
    dimensions: int | None = DEFAULT_EMBEDDING_DIMENSIONS,
) -> list[list[float]]:
    if not texts:
        return []
    payload: dict[str, Any] = {
        "model": model,
        "input": texts,
    }
    if dimensions is not None:
        payload["dimensions"] = dimensions
    request = urllib_request.Request(
        "https://api.openai.com/v1/embeddings",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {_openai_api_key()}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib_request.urlopen(request, timeout=120) as response:
        data = json.loads(response.read().decode("utf-8"))
    items = data.get("data") or []
    vectors: list[list[float]] = []
    for item in items:
        vector = item.get("embedding")
        if not isinstance(vector, list):
            raise RuntimeError("OpenAI embeddings response did not include embedding vectors.")
        vectors.append([float(value) for value in vector])
    if len(vectors) != len(texts):
        raise RuntimeError("OpenAI embeddings response size did not match requested batch size.")
    return vectors


def vector_literal(values: Iterable[float]) -> str:
    return "[" + ",".join(f"{value:.6f}" for value in values) + "]"


def sql_quote(value: str | None) -> str:
    if value is None:
        return "NULL"
    text = str(value)
    tag = "q"
    while f"${tag}$" in text:
        tag += "q"
    return f"${tag}${text}${tag}$"


def _strip_nuls(value: Any) -> Any:
    if isinstance(value, str):
        return value.replace("\x00", "")
    if isinstance(value, list):
        return [_strip_nuls(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_strip_nuls(item) for item in value)
    if isinstance(value, Mapping):
        cleaned: dict[Any, Any] = {}
        for key, item in value.items():
            try:
                cleaned[key] = _strip_nuls(item)
            except Exception:
                cleaned[key] = str(item).replace("\x00", "")
        return cleaned
    if isinstance(value, Sequence) and not isinstance(value, (bytes, bytearray)):
        return [_strip_nuls(item) for item in value]
    return value


def build_schema_sql(table_name: str, vector_dimensions: int) -> str:
    return f"""
CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS {table_name} CASCADE;

CREATE TABLE IF NOT EXISTS {table_name} (
    id BIGSERIAL PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_uri TEXT,
    page_number INTEGER NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    chunk_hash TEXT NOT NULL UNIQUE,
    embedding vector({vector_dimensions}) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS {table_name}_embedding_idx
    ON {table_name}
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

CREATE INDEX IF NOT EXISTS {table_name}_source_idx
    ON {table_name} (source_name, page_number, chunk_index);

ALTER TABLE {table_name}
    DROP COLUMN IF EXISTS clinical_summary;
""".strip()


def build_schema_state_sql() -> str:
    return """
CREATE TABLE IF NOT EXISTS rag_schema_state (
    schema_name TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
""".strip()


def build_schema_version_read_sql(schema_name: str) -> str:
    return f"""
SELECT schema_version
FROM rag_schema_state
WHERE schema_name = {sql_quote(schema_name)};
""".strip()


def build_schema_version_write_sql(schema_name: str, schema_version: int) -> str:
    return f"""
INSERT INTO rag_schema_state (schema_name, schema_version, updated_at)
VALUES ({sql_quote(schema_name)}, {int(schema_version)}, now())
ON CONFLICT (schema_name) DO UPDATE SET
    schema_version = EXCLUDED.schema_version,
    updated_at = EXCLUDED.updated_at;
""".strip()


def build_source_document_schema_sql(table_name: str) -> str:
    return f"""
CREATE TABLE IF NOT EXISTS {table_name} (
    id BIGSERIAL PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_uri TEXT,
    content_hash TEXT NOT NULL UNIQUE,
    content_length INTEGER NOT NULL,
    page_count INTEGER NOT NULL,
    chunk_count INTEGER NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb
);

CREATE INDEX IF NOT EXISTS {table_name}_source_idx
    ON {table_name} (source_name, source_uri);
""".strip()


def build_deferred_ocr_schema_sql(table_name: str) -> str:
    return f"""
CREATE TABLE IF NOT EXISTS {table_name} (
    id BIGSERIAL PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_uri TEXT,
    patient_id TEXT,
    patient_name TEXT,
    pdf_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    page_count INTEGER,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS {table_name}_pdf_id_idx
    ON {table_name} (pdf_id);
""".strip()


def ensure_vector_schema(
    *,
    database_url: str,
    table_name: str,
    source_document_table_name: str,
    vector_dimensions: int,
) -> None:
    print(json.dumps({"stage": "schema_step", "action": "schema_state_bootstrap_start"}, indent=2, sort_keys=True), flush=True)
    run_psql(database_url, build_schema_state_sql())
    print(json.dumps({"stage": "schema_step", "action": "schema_version_read_start", "table_name": table_name}, indent=2, sort_keys=True), flush=True)
    schema_version_result = run_psql(database_url, build_schema_version_read_sql(table_name))
    current_schema_version = None
    if schema_version_result.stdout.strip():
        try:
            current_schema_version = int(schema_version_result.stdout.strip().splitlines()[-1].strip())
        except ValueError:
            current_schema_version = None

    if current_schema_version != DEFAULT_SCHEMA_VERSION:
        print(
            json.dumps(
                {
                    "stage": "schema_step",
                    "action": "schema_rebuild_required",
                    "current_schema_version": current_schema_version,
                    "expected_schema_version": DEFAULT_SCHEMA_VERSION,
                    "table_name": table_name,
                },
                indent=2,
                sort_keys=True,
            ),
            flush=True,
        )
        schema_sql = build_schema_sql(table_name, vector_dimensions)
        source_document_schema_sql = build_source_document_schema_sql(source_document_table_name)
        print(json.dumps({"stage": "schema_step", "action": "schema_rebuild_start", "table_name": table_name, "source_document_table_name": source_document_table_name}, indent=2, sort_keys=True), flush=True)
        run_psql(database_url, schema_sql + "\n\n" + source_document_schema_sql)
        print(json.dumps({"stage": "schema_step", "action": "schema_version_write_start", "table_name": table_name, "schema_version": DEFAULT_SCHEMA_VERSION}, indent=2, sort_keys=True), flush=True)
        run_psql(database_url, build_schema_version_write_sql(table_name, DEFAULT_SCHEMA_VERSION))
    else:
        print(json.dumps({"stage": "schema_step", "action": "source_document_schema_start", "table_name": source_document_table_name}, indent=2, sort_keys=True), flush=True)
        run_psql(database_url, build_source_document_schema_sql(source_document_table_name))
    print(json.dumps({"stage": "schema_step", "action": "schema_bootstrap_done", "table_name": table_name}, indent=2, sort_keys=True), flush=True)


def build_ingest_state_schema_sql(table_name: str) -> str:
    return f"""
CREATE TABLE IF NOT EXISTS {table_name} (
    id BIGSERIAL PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_uri TEXT,
    content_hash TEXT NOT NULL UNIQUE,
    content_length INTEGER NOT NULL,
    page_count INTEGER NOT NULL,
    chunk_count INTEGER NOT NULL,
    status TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb
);

CREATE INDEX IF NOT EXISTS {table_name}_source_idx
    ON {table_name} (source_name, source_uri);
""".strip()


def build_deferred_ocr_upsert_sql(
    table_name: str,
    *,
    source_name: str,
    source_uri: str | None,
    patient_id: str | None,
    patient_name: str | None,
    pdf_id: str,
    filename: str,
    page_count: int | None,
    reason: str,
    metadata: dict[str, Any] | None = None,
) -> str:
    metadata_json = json.dumps(metadata or {}, sort_keys=True)
    return f"""
INSERT INTO {table_name} (
    source_name,
    source_uri,
    patient_id,
    patient_name,
    pdf_id,
    filename,
    page_count,
    reason,
    status,
    metadata
)
VALUES (
    {sql_quote(source_name)},
    {sql_quote(source_uri)},
    {sql_quote(patient_id)},
    {sql_quote(patient_name)},
    {sql_quote(pdf_id)},
    {sql_quote(filename)},
    {('NULL' if page_count is None else str(int(page_count)))},
    {sql_quote(reason)},
    'pending',
    {sql_quote(metadata_json)}
)
ON CONFLICT (pdf_id) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_uri = EXCLUDED.source_uri,
    patient_id = EXCLUDED.patient_id,
    patient_name = EXCLUDED.patient_name,
    filename = EXCLUDED.filename,
    page_count = EXCLUDED.page_count,
    reason = EXCLUDED.reason,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    detected_at = now();
""".strip()


def build_upsert_sql(table_name: str, rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""

    values_sql = []
    for row in rows:
        values_sql.append(
            "("
            + ", ".join(
                [
                    sql_quote(str(row["source_name"])),
                    sql_quote(row.get("source_uri")),
                    str(int(row["page_number"])),
                    str(int(row["chunk_index"])),
                    sql_quote(str(row["chunk_text"])),
                    sql_quote(str(row["chunk_hash"])),
                    sql_quote(str(row["embedding"])),
                    sql_quote(json.dumps(row["metadata"], sort_keys=True)),
                ]
            )
            + ")"
        )

    return f"""
INSERT INTO {table_name} (
    source_name,
    source_uri,
    page_number,
    chunk_index,
    chunk_text,
    chunk_hash,
    embedding,
    metadata
)
VALUES {", ".join(values_sql)}
ON CONFLICT (chunk_hash) DO UPDATE SET
    source_uri = EXCLUDED.source_uri,
    page_number = EXCLUDED.page_number,
    chunk_index = EXCLUDED.chunk_index,
    chunk_text = EXCLUDED.chunk_text,
    embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata;
""".strip()


def build_search_sql(table_name: str) -> str:
    return f"""
SELECT source_name, page_number, chunk_index, chunk_text
FROM {table_name}
ORDER BY embedding <=> (SELECT embedding FROM {table_name} ORDER BY id DESC LIMIT 1)
LIMIT 1;
""".strip()


def build_processed_check_sql(table_name: str, content_hash: str) -> str:
    return f"""
SELECT 1
FROM {table_name}
WHERE content_hash = {sql_quote(content_hash)}
  AND status = 'complete'
LIMIT 1;
""".strip()


def build_mark_processed_sql(
    table_name: str,
    *,
    source_name: str,
    source_uri: str | None,
    content_hash: str,
    content_length: int,
    page_count: int,
    chunk_count: int,
    summary: str,
    metadata: dict[str, Any],
) -> str:
    return f"""
INSERT INTO {table_name} (
    source_name,
    source_uri,
    content_hash,
    content_length,
    page_count,
    chunk_count,
    summary,
    status,
    metadata
)
VALUES (
    {sql_quote(source_name)},
    {sql_quote(source_uri)},
    {sql_quote(content_hash)},
    {content_length},
    {page_count},
    {chunk_count},
    {sql_quote(summary)},
    'complete',
    {sql_quote(json.dumps(metadata, sort_keys=True))}
)
ON CONFLICT (content_hash) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_uri = EXCLUDED.source_uri,
    content_length = EXCLUDED.content_length,
    page_count = EXCLUDED.page_count,
    chunk_count = EXCLUDED.chunk_count,
    summary = EXCLUDED.summary,
    status = EXCLUDED.status,
    processed_at = now(),
    metadata = EXCLUDED.metadata;
""".strip()


def build_source_document_upsert_sql(
    table_name: str,
    *,
    source_name: str,
    source_uri: str | None,
    content_hash: str,
    content_length: int,
    page_count: int,
    chunk_count: int,
    summary: str,
    metadata: dict[str, Any],
) -> str:
    return f"""
INSERT INTO {table_name} (
    source_name,
    source_uri,
    content_hash,
    content_length,
    page_count,
    chunk_count,
    summary,
    status,
    metadata
)
VALUES (
    {sql_quote(source_name)},
    {sql_quote(source_uri)},
    {sql_quote(content_hash)},
    {content_length},
    {page_count},
    {chunk_count},
    {sql_quote(summary)},
    'complete',
    {sql_quote(json.dumps(metadata, sort_keys=True))}
)
ON CONFLICT (content_hash) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_uri = EXCLUDED.source_uri,
    content_length = EXCLUDED.content_length,
    page_count = EXCLUDED.page_count,
    chunk_count = EXCLUDED.chunk_count,
    summary = EXCLUDED.summary,
    status = EXCLUDED.status,
    processed_at = now(),
    metadata = EXCLUDED.metadata;
""".strip()


def build_source_document_backfill_sql(
    table_name: str,
    *,
    source_name: str,
    source_uri: str | None,
    content_hash: str,
    content_length: int,
    page_count: int,
    chunk_count: int,
    summary: str,
    metadata: dict[str, Any],
) -> str:
    return build_source_document_upsert_sql(
        table_name,
        source_name=source_name,
        source_uri=source_uri,
        content_hash=content_hash,
        content_length=content_length,
        page_count=page_count,
        chunk_count=chunk_count,
        clinical_summary=summary,
        metadata=metadata,
    )


def run_psql(database_url: str, sql: str) -> subprocess.CompletedProcess[str]:
    from urllib.parse import unquote, urlparse

    env = os.environ.copy()
    sql_text = sql.strip()
    sql_preview = " ".join(sql_text.split())[:220]

    def _clean(value: str | None) -> str | None:
        if value is None:
            return None
        text = " ".join(str(value).split()).strip()
        return text or None

    def _apply_env_from_shell() -> bool:
        host = _clean(env.get("EVH_PGHOST") or env.get("PGHOST"))
        port = _clean(env.get("EVH_PGPORT") or env.get("PGPORT"))
        user = _clean(env.get("EVH_PGUSER") or env.get("PGUSER"))
        password = _clean(env.get("EVH_PGPASSWORD") or env.get("PGPASSWORD"))
        database = _clean(env.get("EVH_PGDATABASE") or env.get("PGDATABASE"))
        if host:
            env["PGHOST"] = host
        if port:
            env["PGPORT"] = str(port)
        if user:
            env["PGUSER"] = user
        if password:
            env["PGPASSWORD"] = password
        if database:
            env["PGDATABASE"] = database
        if host and "rds.amazonaws.com" in host and not env.get("PGSSLMODE"):
            env["PGSSLMODE"] = "require"
        return bool(host and user and database)

    def _apply_env_from_url(url: str) -> bool:
        normalized = " ".join(url.split())
        try:
            parsed = urlparse(normalized)
        except Exception:
            return False
        if not parsed.scheme.startswith("postgres"):
            return False
        if parsed.hostname:
            env["PGHOST"] = _clean(parsed.hostname) or parsed.hostname
        try:
            port = parsed.port
        except ValueError:
            port = None
        if port:
            env["PGPORT"] = str(port)
        if parsed.username:
            env["PGUSER"] = _clean(unquote(parsed.username)) or unquote(parsed.username)
        if parsed.password:
            env["PGPASSWORD"] = _clean(unquote(parsed.password)) or unquote(parsed.password)
        if parsed.path and parsed.path != "/":
            env["PGDATABASE"] = _clean(parsed.path.lstrip("/")) or parsed.path.lstrip("/")
        if env.get("PGHOST") and "rds.amazonaws.com" in env["PGHOST"] and not env.get("PGSSLMODE"):
            env["PGSSLMODE"] = "require"
        return bool(env.get("PGHOST") and env.get("PGUSER") and env.get("PGDATABASE"))

    def _dsn_from_env() -> str | None:
        host = env.get("PGHOST")
        port = env.get("PGPORT")
        user = env.get("PGUSER")
        password = env.get("PGPASSWORD")
        database = env.get("PGDATABASE")
        if not (host and user and database):
            return None
        parts = [f"host={host}", f"dbname={database}", f"user={user}"]
        if port:
            parts.append(f"port={port}")
        if password:
            parts.append(f"password={password}")
        if env.get("PGSSLMODE"):
            parts.append(f"sslmode={env['PGSSLMODE']}")
        return " ".join(parts)

    def _run_psql_with_args(extra_args: list[str]) -> subprocess.CompletedProcess[str]:
        with tempfile.NamedTemporaryFile("w", suffix=".sql", delete=False, encoding="utf-8") as temp_sql:
            temp_sql.write(sql_text)
            temp_sql_path = temp_sql.name
        try:
            print(
                json.dumps(
                    {
                        "stage": "psql_start",
                        "sql_bytes": len(sql_text.encode("utf-8")),
                        "sql_preview": sql_preview,
                        "extra_args": extra_args,
                        "pg_host": env.get("PGHOST"),
                        "pg_port": env.get("PGPORT"),
                        "pg_user": env.get("PGUSER"),
                        "pg_database": env.get("PGDATABASE"),
                        "pg_sslmode": env.get("PGSSLMODE"),
                    },
                    indent=2,
                    sort_keys=True,
                ),
                flush=True,
            )
            start = time.perf_counter()
            completed = subprocess.run(
                ["psql", "-v", "ON_ERROR_STOP=1", "-q", "-X", "-A", "-t", *extra_args, "-f", temp_sql_path],
                check=True,
                text=True,
                capture_output=True,
                env=env,
                timeout=180,
            )
            elapsed = time.perf_counter() - start
            print(
                json.dumps(
                    {
                        "stage": "psql_done",
                        "elapsed_seconds": round(elapsed, 3),
                        "stdout_bytes": len(completed.stdout or ""),
                        "stderr_bytes": len(completed.stderr or ""),
                        "sql_preview": sql_preview,
                    },
                    indent=2,
                    sort_keys=True,
                ),
                flush=True,
            )
            return completed
        except subprocess.TimeoutExpired as exc:
            print(
                json.dumps(
                    {
                        "stage": "psql_timeout",
                        "timeout_seconds": 180,
                        "sql_preview": sql_preview,
                        "extra_args": extra_args,
                        "error": str(exc),
                    },
                    indent=2,
                    sort_keys=True,
                ),
                file=sys.stderr,
                flush=True,
            )
            raise
        except subprocess.CalledProcessError as exc:
            print(
                json.dumps(
                    {
                        "stage": "psql_failed",
                        "returncode": exc.returncode,
                        "sql_preview": sql_preview,
                        "stdout": (exc.stdout or "")[:2000],
                        "stderr": (exc.stderr or "")[:2000],
                    },
                    indent=2,
                    sort_keys=True,
                ),
                file=sys.stderr,
                flush=True,
            )
            raise
        finally:
            try:
                os.unlink(temp_sql_path)
            except FileNotFoundError:
                pass

    if _apply_env_from_shell():
        try:
            print(json.dumps({"stage": "psql_env_source", "mode": "shell"}, indent=2, sort_keys=True), flush=True)
            return _run_psql_with_args([])
        except subprocess.CalledProcessError:
            raise

    if _apply_env_from_url(database_url):
        try:
            print(json.dumps({"stage": "psql_env_source", "mode": "url"}, indent=2, sort_keys=True), flush=True)
            return _run_psql_with_args([])
        except subprocess.CalledProcessError:
            raise

    dsn = _dsn_from_env()
    if dsn:
        try:
            print(json.dumps({"stage": "psql_env_source", "mode": "dsn"}, indent=2, sort_keys=True), flush=True)
            return _run_psql_with_args([dsn])
        except subprocess.CalledProcessError:
            raise

    sanitized_url = _clean(database_url) or database_url
    try:
        print(json.dumps({"stage": "psql_env_source", "mode": "sanitized_url"}, indent=2, sort_keys=True), flush=True)
        return _run_psql_with_args([sanitized_url])
    except subprocess.CalledProcessError as exc:
        print(
            json.dumps(
                {
                    "stage": "psql_failed",
                    "returncode": exc.returncode,
                    "sql_preview": sql_preview,
                    "stdout": (exc.stdout or "")[:2000],
                    "stderr": (exc.stderr or "")[:2000],
                },
                indent=2,
                sort_keys=True,
            ),
            file=sys.stderr,
            flush=True,
        )
        raise


def has_processed_pdf(database_url: str, table_name: str, content_hash: str) -> bool:
    result = run_psql(database_url, build_processed_check_sql(table_name, content_hash))
    return bool(result.stdout.strip())


def load_into_postgres(
    *,
    database_url: str,
    table_name: str,
    source_document_table_name: str = DEFAULT_SOURCE_DOCUMENT_TABLE_NAME,
    source_name: str,
    source_uri: str | None,
    documents: list[Document],
    vector_dimensions: int,
    embedding_model: str = DEFAULT_EMBEDDING_MODEL,
) -> tuple[float, float]:
    rows: list[dict[str, Any]] = []
    embed_start = perf_counter()
    source_summary: str = ""
    source_summary_kind: str = "structured_only"
    source_page_count = 0
    embeddings = embed_texts_openai(
        [document.page_content for document in documents],
        model=embedding_model,
        dimensions=vector_dimensions,
    )
    for document, embedding in zip(documents, embeddings):
        clean_chunk_text = _strip_nuls(document.page_content)
        clean_metadata = _strip_nuls(
            {
                **document.metadata,
                "source_name": source_name,
                "source_uri": source_uri,
            }
        )
        chunk_hash = hashlib.sha256(
            f"{source_name}:{document.metadata['chunk_index']}:{clean_chunk_text}".encode("utf-8")
        ).hexdigest()
        rows.append(
            {
                "source_name": source_name,
                "source_uri": source_uri,
                "page_number": document.metadata["page_number"],
                "chunk_index": document.metadata["chunk_index"],
                "chunk_text": clean_chunk_text,
                "chunk_hash": chunk_hash,
                "embedding": vector_literal(embedding),
                "metadata": clean_metadata,
            }
        )
        source_summary = _strip_nuls(document.metadata.get("clinical_summary", "") or source_summary)
        source_summary_kind = document.metadata.get("clinical_summary_style", "") or source_summary_kind
        source_page_count = max(source_page_count, int(document.metadata.get("page_number") or 0))
    embedding_seconds = perf_counter() - embed_start

    load_start = perf_counter()
    conn = psycopg.connect(database_url)
    try:
        conn.execute("SET SESSION statement_timeout = 0")
        if documents:
            source_document = documents[0]
            clean_source_name = _strip_nuls(source_name)
            clean_source_uri = _strip_nuls(source_uri)
            clean_summary = _strip_nuls(source_summary)
            clean_source_metadata = _strip_nuls(
                {
                    "patient_id": source_document.metadata.get("patient_id"),
                    "patient_name": source_document.metadata.get("patient_name"),
                    "summary_style": source_summary_kind,
                    "term_summary": source_document.metadata.get("term_summary"),
                    "full_pdf_detected_terms": source_document.metadata.get("full_pdf_detected_terms"),
                }
            )
            conn.execute(
                f"""
                INSERT INTO {source_document_table_name} (
                    source_name,
                    source_uri,
                    content_hash,
                    content_length,
                    page_count,
                    chunk_count,
                    summary,
                    status,
                    metadata
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, 'complete', %s)
                ON CONFLICT (content_hash) DO UPDATE SET
                    source_name = EXCLUDED.source_name,
                    source_uri = EXCLUDED.source_uri,
                    content_length = EXCLUDED.content_length,
                    page_count = EXCLUDED.page_count,
                    chunk_count = EXCLUDED.chunk_count,
                    summary = EXCLUDED.summary,
                    status = EXCLUDED.status,
                    processed_at = now(),
                    metadata = EXCLUDED.metadata
                """,
                (
                    clean_source_name,
                    clean_source_uri,
                    hashlib.sha256((source_uri or source_name).encode("utf-8")).hexdigest(),
                    sum(len(page.page_content) for page in documents),
                    source_page_count,
                    len(documents),
                    clean_summary,
                    json.dumps(
                        clean_source_metadata,
                        sort_keys=True,
                    ),
                ),
            )
        if rows:
            chunk_rows = [
                (
                    _strip_nuls(row["source_name"]),
                    _strip_nuls(row.get("source_uri")),
                    int(row["page_number"]),
                    int(row["chunk_index"]),
                    _strip_nuls(row["chunk_text"]),
                    row["chunk_hash"],
                    row["embedding"],
                    json.dumps(_strip_nuls(row["metadata"]), sort_keys=True),
                )
                for row in rows
            ]
            with conn.cursor() as cur:
                cur.executemany(
                    f"""
                    INSERT INTO {table_name} (
                        source_name,
                        source_uri,
                        page_number,
                        chunk_index,
                        chunk_text,
                        chunk_hash,
                        embedding,
                        metadata
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (chunk_hash) DO UPDATE SET
                        source_uri = EXCLUDED.source_uri,
                        page_number = EXCLUDED.page_number,
                        chunk_index = EXCLUDED.chunk_index,
                        chunk_text = EXCLUDED.chunk_text,
                        embedding = EXCLUDED.embedding,
                        metadata = EXCLUDED.metadata
                    """,
                    chunk_rows,
                )
        conn.commit()
    finally:
        conn.close()
    load_seconds = perf_counter() - load_start
    return embedding_seconds, load_seconds


def mark_pdf_processed(
    *,
    database_url: str,
    table_name: str,
    source_name: str,
    source_uri: str | None,
    content_hash: str,
    content_length: int,
    page_count: int,
    chunk_count: int,
    clinical_summary: str,
    metadata: dict[str, Any],
) -> None:
    run_psql(database_url, build_ingest_state_schema_sql(table_name))
    run_psql(
        database_url,
        build_mark_processed_sql(
            table_name,
            source_name=source_name,
            source_uri=source_uri,
            content_hash=content_hash,
            content_length=content_length,
            page_count=page_count,
            chunk_count=chunk_count,
            clinical_summary=clinical_summary,
            metadata=metadata,
        ),
    )


def benchmark_first_search(database_url: str, table_name: str) -> float:
    search_start = perf_counter()
    run_psql(database_url, build_search_sql(table_name))
    return perf_counter() - search_start


def print_chunk_metadata(documents: list[Document]) -> None:
    seen_keys: set[str] = set()
    for document in documents:
        metadata = document.metadata
        metadata_keywords = sorted(key for key, value in metadata.items() if value is not None and value != "")
        seen_keys.update(metadata_keywords)
        summary = {
            "chunk_index": metadata.get("chunk_index"),
            "page_number": metadata.get("page_number"),
            "patient_id": metadata.get("patient_id"),
            "patient_name": metadata.get("patient_name"),
            "source": metadata.get("source"),
            "metadata_keywords": metadata_keywords,
            "term_summary": metadata.get("term_summary"),
            "detected_terms": metadata.get("detected_terms"),
            "clinical_summary": metadata.get("clinical_summary"),
            "pdf_path": metadata.get("pdf_path"),
            "pdf_url": metadata.get("pdf_url"),
            "chunk_chars": len(document.page_content),
            "preview": document.page_content[:160],
        }
        print(pformat(summary, sort_dicts=False))
    print(pformat({"unique_metadata_keywords": sorted(seen_keys)}, sort_dicts=False))


def _skip_result_json(source_name: str, exc: NoTextLayerError) -> str:
    return json.dumps(
        {
            "source_name": source_name,
            "status": "skipped",
            "status_code": exc.status_code,
            "error": "unexpected pdf structure",
            "page_count": exc.page_count,
        },
        indent=2,
        sort_keys=True,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Chunk a PDF and load enhanced chunks into Postgres/pgvector.")
    parser.add_argument("--database-url", required=True, help="Postgres connection URL for the vector DB.")
    parser.add_argument("--source-name", required=True, help="Human-readable source name for the PDF.")
    parser.add_argument("--pdf-path", help="Local PDF path.")
    parser.add_argument("--pdf-url", help="Remote PDF URL.")
    parser.add_argument("--source-uri", help="Canonical source URI to store with the chunk metadata.")
    parser.add_argument("--dictionary-csv", help="CSV dictionary seed with term_type, canonical_name, and aliases columns.")
    parser.add_argument("--table-name", default=DEFAULT_TABLE_NAME)
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL)
    parser.add_argument("--vector-dimensions", type=int, default=DEFAULT_EMBEDDING_DIMENSIONS)
    parser.add_argument("--chunk-size", type=int, default=1000)
    parser.add_argument("--chunk-overlap", type=int, default=150)
    parser.add_argument(
        "--print-metadata",
        action="store_true",
        help="Print chunk metadata and text previews to the console before loading.",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    source = PatientPdfSource(
        patient_id="benchmark",
        patient_name=args.source_name,
        pdf_path=Path(args.pdf_path) if args.pdf_path else None,
        pdf_url=args.pdf_url,
    )

    extraction_start = perf_counter()
    try:
        pages, page_count = read_pdf_text_from_source(source)
    except NoTextLayerError as exc:
        print(_skip_result_json(args.source_name, exc))
        return 0
    extraction_seconds = perf_counter() - extraction_start

    dictionary_path = Path(args.dictionary_csv) if args.dictionary_csv else None
    term_index = load_term_index(dictionary_path)
    config = ChunkingConfig(chunk_size=args.chunk_size, chunk_overlap=args.chunk_overlap)

    chunking_start = perf_counter()
    documents = chunk_pdf_pages(source, pages, config, term_index=term_index)
    chunking_seconds = perf_counter() - chunking_start
    clinical_summary = documents[0].metadata.get("clinical_summary", "") if documents else generate_veterinary_clinical_summary(source, pages, [])

    if args.print_metadata:
        print_chunk_metadata(documents)

    if args.dry_run:
        print(
            json.dumps(
                {
                    "source_name": args.source_name,
                    "status": "ready",
                    "status_code": 200,
                    "page_count": page_count,
                    "chunk_count": len(documents),
                    "clinical_summary": clinical_summary,
                    "term_summary": documents[0].metadata.get("term_summary", {}) if documents else {},
                    "extraction_seconds": extraction_seconds,
                    "chunking_seconds": chunking_seconds,
                    "vector_dimensions": args.vector_dimensions,
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0

    embedding_seconds, load_seconds = load_into_postgres(
        database_url=args.database_url,
        table_name=args.table_name,
        source_name=args.source_name,
        source_uri=args.source_uri or args.pdf_path or args.pdf_url,
        documents=documents,
        vector_dimensions=args.vector_dimensions,
        embedding_model=args.embedding_model,
    )
    first_search_seconds = benchmark_first_search(args.database_url, args.table_name)

    stats = BenchmarkStats(
        source_name=args.source_name,
        page_count=page_count,
        chunk_count=len(documents),
        extraction_seconds=extraction_seconds,
        chunking_seconds=chunking_seconds,
        embedding_seconds=embedding_seconds,
        load_seconds=load_seconds,
        first_search_seconds=first_search_seconds,
        vector_dimensions=args.vector_dimensions,
        table_name=args.table_name,
    )
    print(json.dumps({**stats.__dict__, "clinical_summary": clinical_summary}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
